{% set version = "1.12.0" %}
{% set name = "RnaSeqSampleSizeData" %}
{% set bioc = "3.6" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: a4840fe556800430b75e34e7a0bfb7c453546f185e4e248bb5ed046c535f3180
build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-edgeR
    - r-base
  run:
    - bioconductor-edgeR
    - r-base
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'MIT + file LICENSE'
  summary: 'Serve data from Bioconductor Objects through a WebSocket connection.'
